import { StyleSheet } from 'react-native';

export default function Options() {

    const styles = StyleSheet.create({
        container: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#ff6600',
        },
        containerlogo: {
            flex: 0.25,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#ff6600',
            width: '100%',
            zIndex: 1,
        },
        containertextfield: {
            flex: 0.75,
            alignItems: 'center',
            backgroundColor: '#F1F1F1',
            borderTopLeftRadius: 30,
            borderTopRightRadius: 40,
            borderBottomLeftRadius: 0,
            borderBottomRightRadius: 0,
            paddingTop: 30,
            width: '100%',
            zIndex: 1,
        },
        containoptions: {
            flex: 1,
            borderRadius: 20,
            height: '70%',
            width: '80%',
            zIndex: 2,
            borderColor: 'gray',
            position: 'absolute',
            top: 100,
            left: "10%",
            backgroundColor: 'white',
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
        },
    
        containlogout: {
            borderRadius: 20,
            height: '10%',
            width: '80%',
            zIndex: 2,
            borderColor: 'gray',
            position: 'absolute',
            top: 700,
            left: "10%",
            backgroundColor: 'white',
            shadowColor: 'rgba(0, 0, 0, 0.2)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
            padding: 20,
        },
        containbox: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            height: "100%"
        },
        containboxlogout: {
            flexDirection: 'row',
            alignItems: 'center',
            height: "100%"
        },
        optionsall: {
            padding: 10,
            height: '10%',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '100%',
            borderColor: 'gray',
            backgroundColor: 'white',
            shadowColor: 'rgba(0, 0, 0, 0.2)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
            flexDirection: 'row',
        },
        optionsname: {
            padding: 30,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            borderBottomLeftRadius: 0,
            borderBottomRightRadius: 0,
            width: '100%',
            borderColor: 'gray',
            backgroundColor: 'white',
            shadowColor: 'rgba(0, 0, 0, 0.2)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
        },
    
        textRegister: {
            fontSize: 20,
            fontWeight: 'bold',
            color: '#ff6600',
            textDecorationLine: 'underline',
        },
        customButton: {
            backgroundColor: 'orange',
            padding: 10,
            borderRadius: 30,
            width: '50%',
            alignItems: 'center',
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
        },
        containButton: {
            width: '100%',
            alignItems: 'center',
            marginBottom: 10,
        },
        containButtonregister: {
            width: '50%',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 10,
            borderColor: '#ff6600',
            backgroundColor: 'white',
            borderWidth: 2,
            borderRadius: 30,
            height: 40,
            shadowColor: 'rgba(0, 0, 0, 0.6)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 7,
        },
        customButtonText: {
            color: 'white',
            fontWeight: 'bold',
            fontSize: 16,
        },
        customButtonTextRegister: {
            color: '#ff6600',
            fontWeight: 'bold',
            fontSize: 16,
        },
    
    });
        

    return { styles }
}

