import { StyleSheet } from 'react-native';

export default function PreviewProduct() {
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            padding: 25,
            backgroundColor: '#ff6600',
        },
        containProduct: {
            padding: 10,
            backgroundColor: 'white',
            borderRadius: 30,
            flex: 0.9,
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.8,
            shadowRadius: 4,
            elevation: 8,
        },
        containHolding: {
            padding: 10,
            backgroundColor: 'white',
            borderRadius: 30,
            flex: 0.9,
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.8,
            shadowRadius: 4,
            elevation: 8,
            alignItems: 'center',
            justifyContent: 'center',
        },
        containButton: {
            // backgroundColor: 'transparent',
            borderRadius: 10,
            flex: 0.1,
            alignItems: 'center',
            justifyContent: 'center',
            flexDirection: 'row',
            width: '100%',
        },
        worker: {
            marginTop: 5,
            padding: 10,
            borderWidth: 1,
            borderColor: '#ddd',
            borderRadius: 10,
        },
        text: {
            color: 'black',
            margin: 5,
            fontWeight: 'bold',
            fontSize: 15,
        },
        textstage: {
            color: 'orange',
            margin: 5,
            fontWeight: 'bold',
            fontSize: 15,
            textDecorationLine: 'underline',
        },
        ButtonLogin: {
            width: '50%',
            alignItems: 'center',
            height: 40,
            margin: 5,
        },
        ButtonAddemp: {
            alignItems: 'center',
            height: 40,
            margin: 5,
        },
        containButtonregister: {
            width: '50%',
            alignItems: 'center',
            justifyContent: 'center',
            borderColor: '#ff6600',
            backgroundColor: 'white',
            borderWidth: 2,
            borderRadius: 30,
            height: 40,
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
            margin: 5,
        },
        containButtonholding: {
            width: '50%',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: 'white',
            borderRadius: 30,
            height: 40,
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
            margin: 5,
        },
        customButtonText: {
            color: 'white',
            fontWeight: 'bold',
            fontSize: 16,
        },
        customButtonTextRegister: {
            color: '#ff6600',
            fontWeight: 'bold',
            fontSize: 16,
        },
        customButtonTextHolding: {
            fontWeight: 'bold',
            fontSize: 16,
        },
        customButton: {
            backgroundColor: 'orange',
            padding: 10,
            borderRadius: 30,
            width: '100%',
            alignItems: 'center',
            shadowColor: 'rgba(0, 0, 0, 0.8)',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.5,
            shadowRadius: 4,
            elevation: 6,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center'
        },
    });
    return { styles }
}
